FROM dronehippie/base:arm

LABEL maintainer="Thomas Boerger <thomas@webhippie.de>" \
  org.opencontainers.image.title="Drone Telegram" \
  org.opencontainers.image.vendor="Webhippie" \
  org.opencontainers.image.documentation="https://dronehippie.github.io/telegram/"

ENTRYPOINT ["/bin/drone-telegram"]
ADD bin/drone-telegram /bin/
