source "https://rubygems.org"

gem "webrick"
gem "jekyll"
gem "jekyll-theme-cayman"

group :jekyll_plugins do
  gem "jekyll-feed"
  gem "github-pages"
end

platforms :mingw, :x64_mingw, :mswin do
  gem "tzinfo"
  gem "tzinfo-data"
  gem "wdm"
end
